
package features;

import config.config;
import internal.session;
import java.awt.Color;
import static java.lang.Math.log;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class login extends javax.swing.JFrame {
int xMouse, yMouse;

    public login() {
        

        initComponents();
        initPlaceholder();
        // Username field with placeholder
       
        }
   
// ================= PLACEHOLDER SYSTEM =================

private void initPlaceholder() {

    setupTextPlaceholder(userTxt, "Enter username or email");

    setupPasswordPlaceholder(JPasswordField, "Enter password");
}


// ---------- TEXT FIELD PLACEHOLDER ----------
private void setupTextPlaceholder(javax.swing.JTextField field, String text) {

    field.setText(text);
    field.setForeground(Color.GRAY);

    field.addFocusListener(new java.awt.event.FocusAdapter() {

        public void focusGained(java.awt.event.FocusEvent evt) {
            if (field.getText().equals(text)) {
                field.setText("");
                field.setForeground(Color.BLACK);
            }
        }

        public void focusLost(java.awt.event.FocusEvent evt) {
            if (field.getText().isEmpty()) {
                field.setText(text);
                field.setForeground(Color.GRAY);
            }
        }
    });
}


// ---------- PASSWORD PLACEHOLDER ----------
private void setupPasswordPlaceholder(javax.swing.JPasswordField field, String text) {

    field.setEchoChar((char) 0);
    field.setText(text);
    field.setForeground(Color.GRAY);

    field.addFocusListener(new java.awt.event.FocusAdapter() {

        public void focusGained(java.awt.event.FocusEvent evt) {
            if (String.valueOf(field.getPassword()).equals(text)) {
                field.setText("");
                field.setForeground(Color.BLACK);
                field.setEchoChar('●');
            }
        }

        public void focusLost(java.awt.event.FocusEvent evt) {
            if (String.valueOf(field.getPassword()).isEmpty()) {
                field.setEchoChar((char) 0);
                field.setText(text);
                field.setForeground(Color.GRAY);
            }
        }
    });
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        hdr = new javax.swing.JPanel();
        xpn = new javax.swing.JPanel();
        xbtn = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lgnpnl = new javax.swing.JPanel();
        loginbtn = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        createnewacc = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        userTxt = new javax.swing.JTextField();
        JPasswordField = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(51, 102, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/.png"))); // NOI18N
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 290, 320));

        hdr.setBackground(new java.awt.Color(255, 255, 255));
        hdr.setMinimumSize(new java.awt.Dimension(800, 50));
        hdr.setPreferredSize(new java.awt.Dimension(810, 50));
        hdr.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                hdrMouseDragged(evt);
            }
        });
        hdr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hdrMousePressed(evt);
            }
        });
        hdr.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        xbtn.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        xbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xbtn.setText("x");
        xbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                xbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                xbtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout xpnLayout = new javax.swing.GroupLayout(xpn);
        xpn.setLayout(xpnLayout);
        xpnLayout.setHorizontalGroup(
            xpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(xbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        xpnLayout.setVerticalGroup(
            xpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(xbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        hdr.add(xpn, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 40, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/56.jpg"))); // NOI18N
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        hdr.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 430, 50));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/output-onlinepngtools__3_-removebg-preview.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        hdr.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, -1));

        bg.add(hdr, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 50));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel3.setPreferredSize(new java.awt.Dimension(300, 300));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sign in to DentalCare");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 380, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel2.setText("Username");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, 20));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel3.setText("Password");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        lgnpnl.setBackground(new java.awt.Color(51, 102, 255));

        loginbtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        loginbtn.setForeground(new java.awt.Color(255, 255, 255));
        loginbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginbtn.setText("Log in");
        loginbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginbtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout lgnpnlLayout = new javax.swing.GroupLayout(lgnpnl);
        lgnpnl.setLayout(lgnpnlLayout);
        lgnpnlLayout.setHorizontalGroup(
            lgnpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        lgnpnlLayout.setVerticalGroup(
            lgnpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        jPanel3.add(lgnpnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 100, 20));

        jLabel6.setForeground(new java.awt.Color(0, 102, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Forgot Password?");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 110, 20));

        createnewacc.setForeground(new java.awt.Color(0, 102, 255));
        createnewacc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        createnewacc.setText("Create new account.");
        createnewacc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createnewaccMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                createnewaccMouseEntered(evt);
            }
        });
        jPanel3.add(createnewacc, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 310, -1));

        jLabel7.setText("Enter your details below.");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        userTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        userTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTxtActionPerformed(evt);
            }
        });
        jPanel3.add(userTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 210, 30));

        JPasswordField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        JPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPasswordFieldActionPerformed(evt);
            }
        });
        jPanel3.add(JPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 210, 30));

        bg.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 380, 470));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 102, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Welcome Back!");
        bg.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 430, 50));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/56.jpg"))); // NOI18N
        bg.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 430, 470));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void hdrMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hdrMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse,y - yMouse);
    }//GEN-LAST:event_hdrMouseDragged

    private void xbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xbtnMouseEntered
        xpn.setBackground(Color. red);
        xbtn.setForeground(Color.white);        // TODO add your handling code here:
    }//GEN-LAST:event_xbtnMouseEntered

    private void xbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xbtnMouseExited
        // TODO add your handling code here:
        xpn.setBackground(Color. white);
        xbtn.setForeground(Color.black);
    }//GEN-LAST:event_xbtnMouseExited

    private void xbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xbtnMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_xbtnMouseClicked

    private void hdrMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hdrMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_hdrMousePressed

    private void createnewaccMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createnewaccMouseEntered

    }//GEN-LAST:event_createnewaccMouseEntered

    private void createnewaccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createnewaccMouseClicked
        // TODO add your handling code here:
        register signup = new register();
        this.dispose();
        signup.setVisible(true);
    }//GEN-LAST:event_createnewaccMouseClicked

    private void loginbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbtnMouseExited
        // TODO add your handling code here:
        lgnpnl.setBackground(Color.blue);
        loginbtn.setForeground(Color.white);
    }//GEN-LAST:event_loginbtnMouseExited

    private void loginbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbtnMouseEntered
        // TODO add your handling code here:
        lgnpnl.setBackground(new Color(147, 199, 237));
        loginbtn.setForeground(Color.white);
    }//GEN-LAST:event_loginbtnMouseEntered

    private void loginbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbtnMouseClicked
      String email = userTxt.getText();
    String rawPass = new String(JPasswordField.getPassword());

    try {
        Connection conn = config.connectDB();

        // Hash the entered password
        String hashedPass = config.hashPassword(rawPass);

        // Query user by email and hashed password
        String sql = "SELECT * FROM tbl_accounts WHERE acc_email=? AND acc_pass=?";
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, email);
        pst.setString(2, hashedPass);

        ResultSet rs = pst.executeQuery();

        if (rs.next()) {

            // Check if email is verified
            String verified = rs.getString("acc_status");
            if (!"1".equals(verified)) {
                JOptionPane.showMessageDialog(this, "Your account is not verified. Please check your email.");
                return;
            }

            // Get role and name
            String role = rs.getString("acc_role");
            String name = rs.getString("acc_name");

            // ✅ ADD SESSION HERE
            int id = rs.getInt("acc_id"); // make sure column name matches your table
            session.setSession(id, name, email, role);

            // Redirect based on role
            switch (role.toLowerCase()) {
                case "patient":
                    patient patientDash = new patient();
                    this.dispose();
                    patientDash.setVisible(true);
                    break;

                case "staff":
                    // Staff staffDash = new Staff(name);
                    // this.dispose();
                    // staffDash.setVisible(true);
                    break;

                case "admin":
                     admin adminDash = new admin();
                    this.dispose();
                     adminDash.setVisible(true);
                    break;

                case "dentist":
                    dentst dentist = new dentst(name);
                    this.dispose();
                    dentist.setVisible(true);
                    break;

                default:
                    JOptionPane.showMessageDialog(this, "Unknown role: " + role);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Invalid Email or Password");
        }

    } catch (Exception e) {
        System.out.println("Login Error: " + e.getMessage());
    }
    }//GEN-LAST:event_loginbtnMouseClicked

    private void userTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTxtActionPerformed

    private void JPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPasswordFieldActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        landingp logo = new landingp();
        this.dispose();
        logo.setVisible(true);
    }//GEN-LAST:event_jLabel10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField JPasswordField;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel createnewacc;
    private javax.swing.JPanel hdr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel lgnpnl;
    private javax.swing.JLabel loginbtn;
    private javax.swing.JTextField userTxt;
    private javax.swing.JLabel xbtn;
    private javax.swing.JPanel xpn;
    // End of variables declaration//GEN-END:variables

  
   

    


    }
