/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package features;

import config.config;
import java.awt.Color;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.table.TableColumn;
import javax.swing.border.Border;

/**
 *
 * @author Cassandra Gallera
 */
public class patient extends javax.swing.JFrame {
 int xMouse, yMouse;
    /**
     * Creates new form log
     * @param name
     */
    public patient(String name) {
        initComponents();
        user.setText("Welcome, " + name);
      
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        dashbox = new javax.swing.JPanel();
        overview = new javax.swing.JPanel();
        ov = new javax.swing.JLabel();
        app_pane = new javax.swing.JPanel();
        app = new javax.swing.JLabel();
        medrec = new javax.swing.JPanel();
        medicalrecords = new javax.swing.JLabel();
        billingpane = new javax.swing.JPanel();
        billing = new javax.swing.JLabel();
        settingpane = new javax.swing.JPanel();
        settings = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        hdr = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        XPNL = new javax.swing.JPanel();
        XBTN = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tab = new javax.swing.JTabbedPane();
        ovtab = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        app_tab = new javax.swing.JPanel();
        medtab = new javax.swing.JPanel();
        bill_tab = new javax.swing.JPanel();
        settings_tab = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(153, 204, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashbox.setBackground(new java.awt.Color(255, 255, 255));
        dashbox.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        overview.setBackground(new java.awt.Color(255, 255, 255));
        overview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                overviewMouseClicked(evt);
            }
        });
        overview.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ov.setBackground(new java.awt.Color(255, 255, 255));
        ov.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ov.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ov.setText("Overview");
        ov.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ovMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ovMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ovMouseExited(evt);
            }
        });
        overview.add(ov, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 30));

        dashbox.add(overview, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, 30));

        app_pane.setBackground(new java.awt.Color(255, 255, 255));
        app_pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        app.setBackground(new java.awt.Color(255, 255, 255));
        app.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        app.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        app.setText("Appointments");
        app.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                appMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                appMouseExited(evt);
            }
        });
        app_pane.add(app, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 30));

        dashbox.add(app_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 170, 30));

        medrec.setBackground(new java.awt.Color(255, 255, 255));

        medicalrecords.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        medicalrecords.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        medicalrecords.setText("Medical Records");
        medicalrecords.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                medicalrecordsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                medicalrecordsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                medicalrecordsMouseExited(evt);
            }
        });

        javax.swing.GroupLayout medrecLayout = new javax.swing.GroupLayout(medrec);
        medrec.setLayout(medrecLayout);
        medrecLayout.setHorizontalGroup(
            medrecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, medrecLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(medicalrecords, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        medrecLayout.setVerticalGroup(
            medrecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, medrecLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(medicalrecords, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        dashbox.add(medrec, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 170, 30));

        billingpane.setBackground(new java.awt.Color(255, 255, 255));

        billing.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        billing.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        billing.setText("Billing");
        billing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                billingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                billingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                billingMouseExited(evt);
            }
        });

        javax.swing.GroupLayout billingpaneLayout = new javax.swing.GroupLayout(billingpane);
        billingpane.setLayout(billingpaneLayout);
        billingpaneLayout.setHorizontalGroup(
            billingpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(billing, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        billingpaneLayout.setVerticalGroup(
            billingpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(billing, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        dashbox.add(billingpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 170, 30));

        settingpane.setBackground(new java.awt.Color(255, 255, 255));

        settings.setBackground(new java.awt.Color(255, 255, 255));
        settings.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        settings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        settings.setText("Settings");
        settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                settingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                settingsMouseExited(evt);
            }
        });

        javax.swing.GroupLayout settingpaneLayout = new javax.swing.GroupLayout(settingpane);
        settingpane.setLayout(settingpaneLayout);
        settingpaneLayout.setHorizontalGroup(
            settingpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(settings, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        settingpaneLayout.setVerticalGroup(
            settingpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(settings, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        dashbox.add(settingpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 170, 30));

        logout.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logout.setText("Logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });
        dashbox.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 427, 170, -1));

        bg.add(dashbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 170, 470));

        hdr.setBackground(new java.awt.Color(255, 255, 255));
        hdr.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                hdrMouseDragged(evt);
            }
        });
        hdr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hdrMousePressed(evt);
            }
        });
        hdr.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/output-onlinepngtools__3_-removebg-preview.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        hdr.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        XBTN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        XBTN.setText("X");
        XBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                XBTNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                XBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                XBTNMouseExited(evt);
            }
        });

        javax.swing.GroupLayout XPNLLayout = new javax.swing.GroupLayout(XPNL);
        XPNL.setLayout(XPNLLayout);
        XPNLLayout.setHorizontalGroup(
            XPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(XBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        XPNLLayout.setVerticalGroup(
            XPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(XBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        hdr.add(XPNL, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 40, 30));

        jLabel2.setBackground(new java.awt.Color(51, 102, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Patient Portal");
        hdr.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 0, 110, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/5046faad4a4c9af72bcf4fe75c8a11d0.jpg"))); // NOI18N
        hdr.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 50));

        bg.add(hdr, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 50));

        ovtab.setBackground(new java.awt.Color(255, 255, 255));
        ovtab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Here's your dental health overview");
        ovtab.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 220, 50));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Next Appointment");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 20));

        jLabel6.setFont(new java.awt.Font("Sylfaen", 1, 16)); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 66, -1, 20));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-calendar-48 (1).png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 50, 50));

        ovtab.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 190, 90));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Total Visits");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 7, -1, 30));

        jLabel9.setFont(new java.awt.Font("Sylfaen", 1, 16)); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("jLabel10");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 66, -1, 20));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-note-40.png"))); // NOI18N
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 50, 50));

        ovtab.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 190, 90));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Account Balance");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 6, -1, 40));

        jLabel12.setFont(new java.awt.Font("Sylfaen", 1, 16)); // NOI18N
        jLabel12.setText("jLabel12");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 30));

        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("jLabel13");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 66, -1, 20));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-us-dollar-30.png"))); // NOI18N
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 26, 50, 40));

        ovtab.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 190, 90));

        user.setBackground(new java.awt.Color(153, 153, 255));
        user.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        user.setForeground(new java.awt.Color(51, 51, 51));
        ovtab.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 170, 50));

        jPanel4.setBackground(new java.awt.Color(51, 51, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Add New Appointment");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 580, 50));

        ovtab.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 600, 50));

        tab.addTab("overview", ovtab);

        javax.swing.GroupLayout app_tabLayout = new javax.swing.GroupLayout(app_tab);
        app_tab.setLayout(app_tabLayout);
        app_tabLayout.setHorizontalGroup(
            app_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 635, Short.MAX_VALUE)
        );
        app_tabLayout.setVerticalGroup(
            app_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        tab.addTab("app", app_tab);

        javax.swing.GroupLayout medtabLayout = new javax.swing.GroupLayout(medtab);
        medtab.setLayout(medtabLayout);
        medtabLayout.setHorizontalGroup(
            medtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 635, Short.MAX_VALUE)
        );
        medtabLayout.setVerticalGroup(
            medtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        tab.addTab("medrec", medtab);

        javax.swing.GroupLayout bill_tabLayout = new javax.swing.GroupLayout(bill_tab);
        bill_tab.setLayout(bill_tabLayout);
        bill_tabLayout.setHorizontalGroup(
            bill_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 635, Short.MAX_VALUE)
        );
        bill_tabLayout.setVerticalGroup(
            bill_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        tab.addTab("billing", bill_tab);

        javax.swing.GroupLayout settings_tabLayout = new javax.swing.GroupLayout(settings_tab);
        settings_tab.setLayout(settings_tabLayout);
        settings_tabLayout.setHorizontalGroup(
            settings_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 635, Short.MAX_VALUE)
        );
        settings_tabLayout.setVerticalGroup(
            settings_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        tab.addTab("settings", settings_tab);

        bg.add(tab, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 640, 520));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void hdrMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hdrMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse,y - yMouse);
    }//GEN-LAST:event_hdrMouseDragged

    private void hdrMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hdrMousePressed
        // TODO add your handling code here:
                xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_hdrMousePressed

    private void XBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XBTNMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_XBTNMouseClicked

    private void XBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XBTNMouseEntered
        // TODO add your handling code here:
        XPNL.setBackground(Color. red);
        XBTN.setForeground(Color.white);
    }//GEN-LAST:event_XBTNMouseEntered

    private void XBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XBTNMouseExited
        // TODO add your handling code here:
        XPNL.setBackground(Color. white);
        XBTN.setForeground(Color.black);
    }//GEN-LAST:event_XBTNMouseExited

    private void ovMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ovMouseEntered
        // TODO add your handling code here:
        overview.setBackground(Color. blue);
                ov.setForeground(Color.white);
    }//GEN-LAST:event_ovMouseEntered

    private void ovMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ovMouseClicked
     tab.setSelectedIndex(0);  
    }//GEN-LAST:event_ovMouseClicked

    private void ovMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ovMouseExited
         overview.setBackground(Color. white);
         ov.setForeground(Color.black);
        
    }//GEN-LAST:event_ovMouseExited

    private void appMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appMouseClicked
       tab.setSelectedIndex(1);  
    }//GEN-LAST:event_appMouseClicked

    private void medicalrecordsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_medicalrecordsMouseClicked
       tab.setSelectedIndex(2);        
    }//GEN-LAST:event_medicalrecordsMouseClicked

    private void billingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billingMouseClicked
       tab.setSelectedIndex(3);       
    }//GEN-LAST:event_billingMouseClicked

    private void settingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsMouseClicked
     tab.setSelectedIndex(4);  
    }//GEN-LAST:event_settingsMouseClicked

    private void appMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appMouseEntered
        app_pane.setBackground(Color. blue);
        app.setForeground(Color.white);
    }//GEN-LAST:event_appMouseEntered

    private void appMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appMouseExited
        app_pane.setBackground(Color. white);
        app.setForeground(Color.black);
    }//GEN-LAST:event_appMouseExited

    private void medicalrecordsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_medicalrecordsMouseEntered
        medrec.setBackground(Color. blue);
        medicalrecords.setForeground(Color.white);
    }//GEN-LAST:event_medicalrecordsMouseEntered

    private void medicalrecordsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_medicalrecordsMouseExited
        medrec.setBackground(Color. white);
        medicalrecords.setForeground(Color.black);
    }//GEN-LAST:event_medicalrecordsMouseExited

    private void billingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billingMouseEntered
        billingpane.setBackground(Color. blue);
        billing.setForeground(Color.white);
    }//GEN-LAST:event_billingMouseEntered

    private void billingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billingMouseExited
        billingpane.setBackground(Color. white);
        billing.setForeground(Color.black);
    }//GEN-LAST:event_billingMouseExited

    private void settingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsMouseEntered
        settingpane.setBackground(Color. blue);
        settings.setForeground(Color.white);
    }//GEN-LAST:event_settingsMouseEntered

    private void settingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsMouseExited
        settingpane.setBackground(Color. white);
        settings.setForeground(Color.black);
    }//GEN-LAST:event_settingsMouseExited

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        landingp home = new landingp();
        this.dispose();
        home.setVisible(true);
    }//GEN-LAST:event_logoutMouseClicked

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        logout.setForeground(Color.red);
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        logout.setForeground(Color.black);
    }//GEN-LAST:event_logoutMouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        landingp logo = new landingp();
        this.dispose();
        logo.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void overviewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_overviewMouseClicked
    
    }//GEN-LAST:event_overviewMouseClicked
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel XBTN;
    private javax.swing.JPanel XPNL;
    private javax.swing.JLabel app;
    private javax.swing.JPanel app_pane;
    private javax.swing.JPanel app_tab;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel bill_tab;
    private javax.swing.JLabel billing;
    private javax.swing.JPanel billingpane;
    private javax.swing.JPanel dashbox;
    private javax.swing.JPanel hdr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel medicalrecords;
    private javax.swing.JPanel medrec;
    private javax.swing.JPanel medtab;
    private javax.swing.JLabel ov;
    private javax.swing.JPanel overview;
    private javax.swing.JPanel ovtab;
    private javax.swing.JPanel settingpane;
    private javax.swing.JLabel settings;
    private javax.swing.JPanel settings_tab;
    private javax.swing.JTabbedPane tab;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables

   

}
