/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package features;

import config.config;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

/**
 *
 * @author Cassandra Gallera
 */
public class register extends javax.swing.JFrame {
int xMouse, yMouse;
    /**
     * Creates new form register
     */
    public register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hdr = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        xpnl = new javax.swing.JPanel();
        xbtn = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        createacc = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        createaccpnl = new javax.swing.JPanel();
        createaccbtn = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        signIN = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        cpass = new javax.swing.JPasswordField();
        pass = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hdr.setBackground(new java.awt.Color(255, 255, 255));
        hdr.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                hdrMouseDragged(evt);
            }
        });
        hdr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hdrMousePressed(evt);
            }
        });
        hdr.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/output-onlinepngtools (3).png"))); // NOI18N
        hdr.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        xpnl.setPreferredSize(new java.awt.Dimension(40, 30));

        xbtn.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        xbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xbtn.setText("X");
        xbtn.setPreferredSize(null);
        xbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                xbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                xbtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout xpnlLayout = new javax.swing.GroupLayout(xpnl);
        xpnl.setLayout(xpnlLayout);
        xpnlLayout.setHorizontalGroup(
            xpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(xbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        xpnlLayout.setVerticalGroup(
            xpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(xbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        hdr.add(xpnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 40, 30));

        getContentPane().add(hdr, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 50));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createacc.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        createacc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        createacc.setText("Create your Account.");
        jPanel2.add(createacc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 360, -1));

        jLabel3.setText("Username");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        jPanel2.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 210, -1));

        jLabel4.setText("E-mail");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 210, -1));

        jLabel5.setText("Password");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jLabel6.setText("Confirm Password");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        createaccpnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createaccpnlMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                createaccpnlMouseEntered(evt);
            }
        });
        createaccpnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createaccbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        createaccbtn.setText("Create Account");
        createaccbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createaccbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                createaccbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                createaccbtnMouseExited(evt);
            }
        });
        createaccpnl.add(createaccbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, 0, 350, 30));

        jPanel2.add(createaccpnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 130, 30));

        jLabel8.setText("Already have an account?");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, 20));

        signIN.setForeground(new java.awt.Color(51, 102, 255));
        signIN.setText("Sign in");
        signIN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signINMouseClicked(evt);
            }
        });
        jPanel2.add(signIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 70, 20));

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCheckBox1.setText(" Accept the terms and policies");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 210, 30));

        cpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpassActionPerformed(evt);
            }
        });
        jPanel2.add(cpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 210, 30));

        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        jPanel2.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 212, 210, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 350, 430));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/13.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 470));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 810, 470));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void hdrMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hdrMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse,y - yMouse);
    }//GEN-LAST:event_hdrMouseDragged

    private void xbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xbtnMouseClicked
        // TODO add your handling code here:
        System.exit(0);
        
        
    }//GEN-LAST:event_xbtnMouseClicked

    private void xbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xbtnMouseExited
        // TODO add your handling code here:
       
        xpnl.setBackground(Color. white);
        xbtn.setForeground(Color.black);
    }//GEN-LAST:event_xbtnMouseExited

    private void xbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xbtnMouseEntered
        // TODO add your handling code here:
        xpnl.setBackground(Color. red);
        xbtn.setForeground(Color.white);
    }//GEN-LAST:event_xbtnMouseEntered

    private void hdrMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hdrMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_hdrMousePressed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void signINMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signINMouseClicked
        // TODO add your handling code here:
        admin signin = new admin();
        this.dispose();
        signin.setVisible(true);
    }//GEN-LAST:event_signINMouseClicked

    private void createaccbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createaccbtnMouseClicked


    String usern = username.getText();
    String eml = email.getText();
    String rawPass = new String(pass.getPassword());
    String confirmRaw = new String(cpass.getPassword());


    if (usern.isEmpty() || eml.isEmpty() || rawPass.isEmpty() || confirmRaw.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill in all fields");
        return;
    }

    if (!rawPass.equals(confirmRaw)) {
        JOptionPane.showMessageDialog(this, "Passwords do not match");
        return;
    }

    try {
        config db = new config();

        String checkSql = "SELECT COUNT(*) FROM t_users WHERE eml=?";
        double count = db.getSingleValue(checkSql, eml);

        if (count > 0) {
            JOptionPane.showMessageDialog(this, "Email is already in use. Please use another email.");
            return;
        }

        final JDialog loading = new JDialog(this, "Sending OTP...", true);
        JLabel lbl = new JLabel("Please wait, sending OTP to your email...");
        lbl.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        loading.add(lbl);
        loading.pack();
        loading.setLocationRelativeTo(this);


        SwingWorker<Boolean, Void> worker = new SwingWorker<Boolean, Void>() {
            String otp = config.generateOtp();

            @Override
            protected Boolean doInBackground() {
                return config.sendOtpEmail(eml, otp);
            }

            @Override
            protected void done() {
                loading.dispose(); 
                try {
                    boolean sent = get();
                    if (!sent) {
                        JOptionPane.showMessageDialog(null, "Failed to send OTP. Please try again later.");
                        return;
                    }

                    
                    String inputOtp = JOptionPane.showInputDialog(null, "Enter the OTP sent to your email:");

                    if (inputOtp != null && inputOtp.equals(otp)) {
                        
                        String hashedPass = config.hashPassword(rawPass);

                        String sql = "INSERT INTO t_users(usern, eml, pass, role) "
                                   + "VALUES(?,?,?,'customer')";

                        db.addRecord(sql, usern, eml,hashedPass);

                        JOptionPane.showMessageDialog(null, "Sign Up Successful! Your account is verified.");
                        dispose();
                        new login().setVisible(true);

                    } else {
                        JOptionPane.showMessageDialog(null, "Incorrect OTP. Account creation failed.");
                    }

                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
                }
            }
        };

        worker.execute();
        loading.setVisible(true);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_createaccbtnMouseClicked

    private void cpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpassActionPerformed

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    private void createaccpnlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createaccpnlMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_createaccpnlMouseClicked

    private void createaccpnlMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createaccpnlMouseEntered
        // TODO add your handling code here:
         
    }//GEN-LAST:event_createaccpnlMouseEntered

    private void createaccbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createaccbtnMouseEntered
        // TODO add your handling code here:
         createaccpnl.setBackground(new Color(147, 199, 237));
         createaccbtn.setForeground(Color.blue);
    }//GEN-LAST:event_createaccbtnMouseEntered

    private void createaccbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createaccbtnMouseExited
         createaccpnl.setBackground(new Color(240,240,240));
         createaccbtn.setForeground(Color.black);
    }//GEN-LAST:event_createaccbtnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField cpass;
    private javax.swing.JLabel createacc;
    private javax.swing.JLabel createaccbtn;
    private javax.swing.JPanel createaccpnl;
    private javax.swing.JTextField email;
    private javax.swing.JPanel hdr;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField pass;
    private javax.swing.JLabel signIN;
    private javax.swing.JTextField username;
    private javax.swing.JLabel xbtn;
    private javax.swing.JPanel xpnl;
    // End of variables declaration//GEN-END:variables
}
